# Generated by Django 6.1 on 2026-09-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenus", "0012_documentpermanent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemaineCahier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_lundi", models.DateField(verbose_name="lundi de la semaine")),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="À laisser vide pour les semaines de vacances.",
                        null=True,
                        verbose_name="n° de semaine pédagogique",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Semaine de cours"),
                            ("VACANCES", "Vacances"),
                        ],
                        default="NORMALE",
                        max_length=10,
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text="Ex. « Vacances de la Toussaint ».",
                        max_length=100,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "annee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semaines_cahier",
                        to="contenus.anneescolaire",
                        verbose_name="année scolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "semaine du cahier de texte",
                "verbose_name_plural": "semaines du cahier de texte",
                "ordering": ["date_lundi"],
            },
        ),
        migrations.CreateModel(
            name="EntreeCahier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rubrique",
                    models.CharField(
                        choices=[
                            ("COURS", "Cours"),
                            ("IC", "Interrogation de cours"),
                            ("TD", "TD"),
                            ("TP", "TP"),
                            ("AP", "Accompagnement personnalisé"),
                            ("DS", "Devoir surveillé"),
                            ("DM", "Devoir maison"),
                            ("CC", "Cahier de calcul"),
                            ("PC", "Programme de colle"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "jour",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "lundi"),
                            (1, "mardi"),
                            (2, "mercredi"),
                            (3, "jeudi"),
                            (4, "vendredi"),
                        ],
                        help_text="À laisser vide pour une rubrique hebdomadaire (CC, programme de colle).",
                        null=True,
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Pour ordonner plusieurs entrées dans la même case.",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Séance normale"),
                            ("FERIE", "Férié"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="NORMALE",
                        max_length=10,
                    ),
                ),
                (
                    "texte",
                    models.CharField(
                        blank=True,
                        help_text="Complément libre, ou libellé complet si aucun document n'est lié.",
                        max_length=200,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "cahier_calcul",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.cahiercalcul",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.cours",
                    ),
                ),
                (
                    "devoir",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.devoir",
                    ),
                ),
                (
                    "fiche_outil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.ficheoutil",
                    ),
                ),
                (
                    "programme_colle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.programmecolle",
                    ),
                ),
                (
                    "tp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_cahier",
                        to="contenus.tp",
                    ),
                ),
                (
                    "semaine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrees",
                        to="cahier_texte.semainecahier",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée du cahier de texte",
                "verbose_name_plural": "entrées du cahier de texte",
                "ordering": [
                    "semaine__date_lundi",
                    models.OrderBy(models.F("jour"), nulls_first=True),
                    "ordre",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="semainecahier",
            constraint=models.UniqueConstraint(
                fields=("annee", "date_lundi"), name="cahier_semaine_unique_par_annee"
            ),
        ),
    ]
