# Generated by Django 6.1 on 2026-09-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cahier_texte", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreecahier",
            name="texte",
            field=models.TextField(
                blank=True,
                help_text="Ce qui a été traité en séance, une ligne par point. Inutile d'y remettre le titre du document lié : il est affiché automatiquement au-dessus.",
                verbose_name="détail",
            ),
        ),
    ]
