# Generated by Django 6.1 on 2026-09-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahier_texte', '0002_alter_entreecahier_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreecahier',
            name='titre',
            field=models.CharField(blank=True, help_text="Laisser vide pour reprendre le titre du document lié. Rempli, il s'affiche à sa place.", max_length=200, verbose_name='titre'),
        ),
    ]
