# Generated by Django 6.1 on 2026-08-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='ex : 2025-2026', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_courante', models.BooleanField(default=False, help_text='Une seule année doit être marqué courante.')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage, 0 en premier")),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DM', 'Devoir maison'), ('DS', 'Devoir surveillé'), ('IC', 'Interrogation de cours')], max_length=2)),
                ('titre', models.CharField(help_text="Ex : 'DS n°3' ou 'DM — Fonctions dérivées'", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('fichier_sujet', models.FileField(upload_to='devoirs/sujets/')),
                ('fichier_correction', models.FileField(blank=True, null=True, upload_to='devoirs/corrections/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoirs', to='contenus.anneescolaire')),
                ('themes', models.ManyToManyField(blank=True, related_name='devoirs', to='contenus.theme')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='FicheOutil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_outils', to='contenus.anneescolaire')),
            ],
            options={
                'verbose_name': 'Fiche outil',
                'verbose_name_plural': 'Fiches outils',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='FichierOutil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='fiches_outils/')),
                ('legende', models.CharField(blank=True, help_text="Ex : 'Formulaire' ou 'Annexe 1' — optionnel.", max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('fiche_outil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='contenus.ficheoutil')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fichier_sujet', models.FileField(upload_to='tp/sujets/')),
                ('fichier_corrige', models.FileField(blank=True, null=True, upload_to='tp/corriges/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tp', to='contenus.anneescolaire')),
                ('themes', models.ManyToManyField(blank=True, related_name='tp', to='contenus.theme')),
            ],
            options={
                'verbose_name': 'TP',
                'verbose_name_plural': 'TP',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Peut contenir des url en txt simple, pas de format enrichi pour le moment')),
                ('fichier_accompagnement', models.FileField(upload_to='cours/fichier_accompagnement/')),
                ('fichier_td', models.FileField(upload_to='cours/td/')),
                ('date_publication', models.DateTimeField(auto_now=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='contenus.anneescolaire')),
                ('devoirs_lies', models.ManyToManyField(blank=True, related_name='cours_lies', to='contenus.devoir')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='contenus.theme')),
                ('tp_lies', models.ManyToManyField(blank=True, related_name='cours_lies', to='contenus.tp')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
