# Generated by Django 6.1 on 2026-08-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_publication'], 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
    ]
