# Generated by Django 6.1 on 2026-08-11 22:30

import contenus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0002_alter_cours_options_alter_theme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AlterField(
            model_name='cours',
            name='annee_scolaire',
            field=models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='contenus.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='annee_scolaire',
            field=models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='devoirs', to='contenus.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='ficheoutil',
            name='annee_scolaire',
            field=models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='fiches_outils', to='contenus.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='annee_scolaire',
            field=models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='tp', to='contenus.anneescolaire'),
        ),
    ]
