# Generated by Django 6.1 on 2026-08-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0003_alter_anneescolaire_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, help_text="Si vide sera complété automatiquement. Ex 'E1_24-25' pour le E1 de l'année 2024-2025", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='slug',
            field=models.SlugField(blank=True, help_text="Si vide sera complété automatiquement. Ex 'DM-3_24-25' pour le DM 3 de l'année 2024-2025", max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='tp',
            name='slug',
            field=models.SlugField(blank=True, help_text="Si vide sera complété automatiquement. Ex 'TP1_24-25' pour le TP 1 de l'année 2024-2025", max_length=210, unique=True),
        ),
    ]
