# Generated by Django 6.1 on 2026-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0004_alter_cours_slug_alter_devoir_slug_alter_tp_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_publication']},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='fichier_accompagnement',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='fichier_td',
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier_cours_eleve',
            field=models.FileField(blank=True, null=True, upload_to='cours/fiches/', verbose_name='Fiche de cours — version élève'),
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier_cours_prof',
            field=models.FileField(blank=True, null=True, upload_to='cours/fiches/', verbose_name='Fiche de cours — version complète'),
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier_manip',
            field=models.FileField(blank=True, null=True, upload_to='cours/manips/', verbose_name='Manipulation de cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier_td_eleve',
            field=models.FileField(blank=True, null=True, upload_to='cours/td/', verbose_name='Fiche de TD — version élève'),
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier_td_prof',
            field=models.FileField(blank=True, null=True, upload_to='cours/td/', verbose_name='Fiche de TD — version complète'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, unique=True),
        ),
    ]
