# Generated by Django 6.1 on 2026-09-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0005_alter_cours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
    ]
