# Generated by Django 6.1 on 2026-09-04 20:56

import contenus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0006_alter_cours_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeColle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveIntegerField(help_text='Numéro de la semaine (1, 2, 3…)')),
                ('titre', models.CharField(help_text="Ex : 'Semaine 12 — Électrocinétique et mécanique'", max_length=200)),
                ('fichier', models.FileField(upload_to='colles/programmes/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='programmes_colles', to='contenus.anneescolaire')),
            ],
            options={
                'verbose_name': 'Programme de colle',
                'verbose_name_plural': 'Programmes de colles',
                'ordering': ['-semaine'],
            },
        ),
    ]
