# Generated by Django 6.1 on 2026-09-06 12:19

import contenus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0007_programmecolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveIntegerField(help_text='Numéro de la semaine (1, 2, 3…)')),
                ('titre', models.CharField(blank=True, help_text="Facultatif. Ex : 'Dérivées et primitives'", max_length=200)),
                ('fichier_sujet', models.FileField(upload_to='calcul/sujets/')),
                ('fichier_corrige', models.FileField(blank=True, null=True, upload_to='calcul/corriges/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(default=contenus.models.annee_scolaire_courante, on_delete=django.db.models.deletion.PROTECT, related_name='cahiers_calcul', to='contenus.anneescolaire')),
            ],
            options={
                'verbose_name': 'Cahier de calcul',
                'verbose_name_plural': 'Cahiers de calcul',
                'ordering': ['-semaine'],
            },
        ),
    ]
