# Generated by Django 6.1 on 2026-09-07 15:01

import contenus.fichiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0008_cahiercalcul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='fichier_cours_eleve',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('fiche', 'cours-eleve'), verbose_name='Fiche de cours — version élève'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_cours_prof',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('fiches', 'cours-prof'), verbose_name='Fiche de cours — version complète'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_manip',
            field=models.FileField(blank=True, null=True, upload_to=contenus.fichiers.CheminMedia('manips', 'manip'), verbose_name='Manipulation de cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_td_eleve',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('td', 'td-eleve'), verbose_name='Fiche de TD — version élève'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_td_prof',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('td', 'td-prof'), verbose_name='Fiche de TD — version complète'),
        ),
    ]
