# Generated by Django 6.1 on 2026-09-07 15:42

import contenus.fichiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0009_alter_cours_fichier_cours_eleve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='fichier_python_corrige',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('tp', 'tp-prof-python')),
        ),
        migrations.AddField(
            model_name='tp',
            name='fichier_python_sujet',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('tp', 'tp-eleve-python')),
        ),
        migrations.AlterField(
            model_name='cahiercalcul',
            name='fichier_corrige',
            field=models.FileField(blank=True, null=True, upload_to=contenus.fichiers.CheminMedia('cahier-calcul/', 'correction')),
        ),
        migrations.AlterField(
            model_name='cahiercalcul',
            name='fichier_sujet',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cahier-calcul/', 'sujet')),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_cours_eleve',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cours', 'cours-eleve'), verbose_name='Fiche de cours — version élève'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_cours_prof',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cours', 'cours-prof'), verbose_name='Fiche de cours — version complète'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_manip',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cours', 'manip'), verbose_name='Manipulation de cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_td_eleve',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cours', 'td-eleve'), verbose_name='Fiche de TD — version élève'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_td_prof',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('cours', 'td-prof'), verbose_name='Fiche de TD — version complète'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='fichier_correction',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('devoirs', 'correction')),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='fichier_sujet',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('devoirs', 'sujet')),
        ),
        migrations.AlterField(
            model_name='fichieroutil',
            name='fichier',
            field=models.FileField(storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('fiches_outils', '')),
        ),
        migrations.AlterField(
            model_name='programmecolle',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('colles/programmes/', '')),
        ),
        migrations.AlterField(
            model_name='tp',
            name='fichier_corrige',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('tp', 'tp-prof')),
        ),
        migrations.AlterField(
            model_name='tp',
            name='fichier_sujet',
            field=models.FileField(blank=True, null=True, storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('tp', 'tp-eleve')),
        ),
    ]
