# Generated by Django 6.1 on 2026-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenus", "0010_tp_fichier_python_corrige_tp_fichier_python_sujet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmecolle",
            name="slug",
            field=models.SlugField(blank=True, max_length=210, unique=True),
        ),
    ]
