# Generated by Django 6.1 on 2026-09-10 13:17

import contenus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenus", "0011_programmecolle_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPermanent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("formules", "Formules"),
                            ("questions", "Questions de cours"),
                        ],
                        help_text="Un seul document par type.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("fichier", models.FileField(upload_to="colle/documents/")),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        default=contenus.models.annee_scolaire_courante,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_permanents",
                        to="contenus.anneescolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document permanent",
                "verbose_name_plural": "Documents permanents",
                "ordering": ["type"],
            },
        ),
    ]
