# Generated by Django 6.1 on 2026-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0012_documentpermanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahiercalcul',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, unique=True),
        ),
    ]
