# Generated by Django 6.1 on 2026-09-17 09:56

# Generated by Django 6.1 on 2026-09-17 09:56

import contenus.fichiers
from django.db import migrations, models
from django.utils.text import slugify


def peupler_slugs(apps, schema_editor):
    FichierOutil = apps.get_model('contenus', 'FichierOutil')
    for fichier in FichierOutil.objects.all():
        base = slugify(fichier.legende) or "fichier"
        pris = set(
            FichierOutil.objects
            .filter(fiche_outil_id=fichier.fiche_outil_id)
            .exclude(pk=fichier.pk)
            .values_list('slug', flat=True)
        )
        candidat, compteur = base, 2
        while candidat in pris:
            candidat, compteur = f"{base}-{compteur}", compteur + 1
        fichier.slug = candidat
        fichier.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0013_cahiercalcul_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichieroutil',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=60),
        ),
        migrations.RunPython(peupler_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fichieroutil',
            name='fichier',
            field=models.FileField(storage=contenus.fichiers.StockageEcrasement(), upload_to=contenus.fichiers.CheminMedia('fiches_outils', '', attribut='chemin_base')),
        ),
        migrations.AddConstraint(
            model_name='fichieroutil',
            constraint=models.UniqueConstraint(fields=('fiche_outil', 'slug'), name='slug_unique_par_fiche_outil'),
        ),
    ]