# Generated by Django 6.1 on 2026-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0014_fichieroutil_slug_alter_fichieroutil_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icone',
            field=models.CharField(blank=True, default='file', help_text="Nom d'une icône Tabler sans le préfixe « ti- ». Ex : telescope, cpu, flask, wave-sine, magnet. Catalogue sur tabler.io/icons", max_length=50),
        ),
    ]
