# Generated by Django 6.1 on 2026-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenus', '0015_theme_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermanent',
            name='fichier_vide',
            field=models.FileField(default=1, upload_to='colle/documents/'),
            preserve_default=False,
        ),
    ]
