# Generated by Django 6.1 on 2026-09-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenus', '0007_programmecolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['matiere', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'matiere'), name='colleur_unique_par_matiere')],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('horaire', models.CharField(help_text='Ex : 12h, 17h30', max_length=20)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux_colle', to='contenus.anneescolaire')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='colloscope.colleur')),
            ],
            options={
                'ordering': ['jour', 'horaire', 'colleur__nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeColle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : T1, B3', max_length=10)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes_colle', to='contenus.anneescolaire')),
            ],
            options={
                'verbose_name': 'Groupe de colle',
                'verbose_name_plural': 'Groupes de colle',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ImportColloscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='colloscope/imports/')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports_colloscope', to='contenus.anneescolaire')),
            ],
            options={
                'verbose_name': 'Import de colloscope',
                'verbose_name_plural': 'Imports de colloscope',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveIntegerField()),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='colloscope.creneau')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='colloscope.groupecolle')),
            ],
            options={
                'ordering': ['semaine', 'creneau__jour', 'creneau__horaire'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupecolle',
            constraint=models.UniqueConstraint(fields=('nom', 'annee_scolaire'), name='groupe_unique_par_annee'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('creneau', 'semaine'), name='un_seul_groupe_par_creneau_et_semaine'),
        ),
    ]
