# Generated by Django 6.1 on 2026-09-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloscope', '0001_initial'),
        ('contenus', '0007_programmecolle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['semaine__numero', 'creneau__jour', 'creneau__horaire']},
        ),
        migrations.RenameField(
            model_name='importcolloscope',
            old_name='fichier',
            new_name='fichier_colloscope',
        ),
        migrations.AddField(
            model_name='importcolloscope',
            name='fichier_eleves',
            field=models.FileField(default='', upload_to='colloscope/imports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importcolloscope',
            name='fichier_semaines',
            field=models.FileField(default='', upload_to='colloscope/imports/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='contenus.anneescolaire')),
                ('groupes', models.ManyToManyField(related_name='eleves', to='colloscope.groupecolle')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_debut', models.DateField(help_text='Lundi de la semaine.')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semaines_colle', to='contenus.anneescolaire')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='passage',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='colloscope.semaine'),
        ),
        migrations.AddConstraint(
            model_name='semaine',
            constraint=models.UniqueConstraint(fields=('numero', 'annee_scolaire'), name='semaine_unique_par_annee'),
        ),
    ]
