# Generated by Django 6.1 on 2026-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colloscope', '0002_alter_passage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneau',
            options={'ordering': ['jour', 'horaire', 'colleur__nom'], 'verbose_name': 'Créneau', 'verbose_name_plural': 'Créneaux'},
        ),
        migrations.RemoveConstraint(
            model_name='groupecolle',
            name='groupe_unique_par_annee',
        ),
        migrations.RemoveConstraint(
            model_name='semaine',
            name='semaine_unique_par_annee',
        ),
        migrations.RemoveField(
            model_name='creneau',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='importcolloscope',
            name='annee_scolaire',
        ),
        migrations.AddField(
            model_name='importcolloscope',
            name='libelle_annee',
            field=models.CharField(default='', help_text='Affiché en tête du colloscope. Ex : 2025-2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupecolle',
            name='nom',
            field=models.CharField(help_text='Ex : T1, B3', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='groupecolle',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='semaine',
            name='annee_scolaire',
        ),
    ]
